### ISSUE TITLE
Use logging instead of System.out.println

### ISSUE THREAD

**Issue by KonradHoeffner** [LodLive/LodView#49]
There are still several places, where System.out.println is used, which then aren't configurable using logging configuration files.

```
ack -l -c "System.out.println" 
src/main/java/org/dvcama/lodview/controllers/LinkedResourcesController.java:2
src/main/java/org/dvcama/lodview/controllers/StaticController.java:1
src/main/java/org/dvcama/lodview/controllers/ResourceController.java:9
src/main/java/org/dvcama/lodview/controllers/LodController.java:3
src/main/java/org/dvcama/lodview/controllers/ErrorController.java:4
src/main/java/org/dvcama/lodview/bean/OntologyBean.java:7
src/main/java/org/dvcama/lodview/conf/ConfigurationBean.java:1
src/main/java/org/dvcama/lodview/endpoint/SPARQLEndPoint.java:11
```

**Comment by KonradHoeffner** [comment]
Resolved in pull request https://github.com/LodLive/LodView/pull/50

**Comment by dvcama** [comment]
This probably helped with the log4j vulnerabilities (Log4j 1.x and Log4J 2.x) ... 
Probably it makes sense waiting to update Jena (that will not be painless) as you suggested here https://github.com/LodLive/LodView/issues/52
